import { Server, Route, HardDrive, Cable, PlugZap, Monitor, Keyboard, Thermometer, Network } from "lucide-react";

export const rackDevices = [
        {
            id: 'cisco-isr4331',
            title: 'Cisco ISR4331 Router',
            shortLabel: 'Cisco ISR4331',
            startU: 42,
            sizeU: 1,
            icon: Route,
            type: 'Network',
            description: 'The rack edge router, handling WAN connectivity, routing policy, firewalling, VPN services, and traffic between the homelab and upstream networks.',
            details: ['1U integrated services router', '100 Mbps base performance, upgradeable to 300 Mbps', 'Modular NIM and service-module expansion'],
            electrical: ['Input: 100–240 V AC, 47–63 Hz', 'Typical draw: 42 W without modules', 'Maximum: 250 W with standard AC PSU; up to 530 W with PoE PSU'],
        },
        {
            id: 'patch-41',
            title: 'Patch Panel',
            shortLabel: 'U41 Patch Panel',
            startU: 41,
            sizeU: 1,
            icon: Cable,
            type: 'Passive',
            description: 'A passive termination point between the edge router and core switch that keeps permanent cabling fixed while short patch leads handle equipment changes.',
            details: ['U41 position', 'Passive structured-cabling termination', 'Router and core-switch patching'],
        },
        {
            id: 'cisco-catalyst-3850',
            title: 'Cisco Catalyst 3850',
            shortLabel: 'Catalyst 3850',
            startU: 40,
            sizeU: 1,
            icon: Network,
            type: 'Network',
            description: 'The primary managed switching platform for VLANs, inter-device connectivity, and access-layer services across the rack.',
            details: ['1U managed campus switch', 'StackWise and modular uplink support vary by model', 'PoE capacity depends on exact chassis and installed PSU'],
            electrical: ['Input: 100–240 V AC for 350/715 W PSUs; 115–240 V AC for 1,100 W PSU', 'Frequency: 50–60 Hz', 'Supported PSUs: 350 W, 715 W, 1,100 W AC, or 440 W DC depending on model'],
        },
        {
            id: 'patch-39',
            title: 'Patch Panel',
            shortLabel: 'U39 Patch Panel',
            startU: 39,
            sizeU: 1,
            icon: Cable,
            type: 'Passive',
            description: 'A dedicated passive cross-connect for organizing copper runs and presenting them cleanly to the adjacent switching equipment.',
            details: ['U39 position', 'Passive structured-cabling termination', 'Short patch-lead connection to active equipment'],
        },
        {
            id: 'patch-38',
            title: 'Patch Panel',
            shortLabel: 'U38 Patch Panel',
            startU: 38,
            sizeU: 1,
            icon: Cable,
            type: 'Passive',
            description: 'A second adjacent passive cross-connect that separates cable groups and reduces strain on the switch-facing patch leads.',
            details: ['U38 position', 'Passive structured-cabling termination', 'Cable-group separation and organization'],
        },
        {
            id: 'tp-link-sg3428',
            title: 'TP-Link SG3428',
            shortLabel: 'TP-Link SG3428',
            startU: 37,
            sizeU: 1,
            icon: Network,
            type: 'Network',
            description: 'A fanless managed access switch that adds copper ports and SFP uplinks for lab clients, appliances, and segmented test networks.',
            details: ['24 × Gigabit RJ45 ports', '4 × Gigabit SFP slots', '56 Gbps switching capacity'],
            electrical: ['Input: 100–240 V AC, 50/60 Hz', 'Maximum draw: approximately 20 W (hardware revision dependent)', 'Fanless internal power supply'],
        },
        {
            id: 'patch-36',
            title: 'Patch Panel',
            shortLabel: 'U36 Patch Panel',
            startU: 36,
            sizeU: 1,
            icon: Cable,
            type: 'Passive',
            description: 'The lower network-section patch panel, providing a fixed termination point for connections served by the TP-Link switch.',
            details: ['U36 position', 'Passive structured-cabling termination', 'Access-switch patching'],
        },
        {
            id: 'apc-netbotz-570',
            title: 'APC NetBotz Rack Monitor 570',
            shortLabel: 'APC NetBotz 570',
            startU: 35,
            sizeU: 1,
            icon: Thermometer,
            type: 'Telemetry',
            description: 'The environmental and physical-security hub for collecting temperature, humidity, leak, door, camera, and auxiliary sensor data from the rack.',
            details: ['Supports external sensor and camera pods', 'Six universal sensor ports', 'Networked alerting and environmental telemetry'],
            electrical: ['Input: 100–240 V AC, 50/60 Hz', 'Maximum total current: 2 A', 'Sensor outputs: 12/24 V DC; A-Link 24 V output up to 1,000 mA'],
        },
        {
            id: 'cable-management-34',
            title: 'Cable Management Panel',
            shortLabel: 'U34 Cable Mgmt',
            startU: 34,
            sizeU: 1,
            icon: Cable,
            type: 'Passive',
            description: 'A horizontal routing channel that controls bend radius, strain, and patch-lead paths below the active network stack.',
            details: ['U34 position', 'Passive horizontal cable routing', 'Patch-lead strain relief and organization'],
        },
        {
            id: 'blank-30',
            title: 'Blank Panel',
            shortLabel: 'U30 Blank Panel',
            startU: 30,
            sizeU: 1,
            icon: Server,
            type: 'Passive',
            description: 'A solid filler panel that closes an unused rack unit, improves front-to-back airflow discipline, and visually separates the network and console zones.',
            details: ['U30 position', 'Passive airflow management', 'Closes one unused rack unit'],
        },
        {
            id: 'dell-monitor',
            title: 'Dell Monitor',
            shortLabel: 'Dell Monitor',
            startU: 26,
            sizeU: 4,
            icon: Monitor,
            type: 'Console',
            description: 'A locally mounted Dell display for firmware setup, direct server administration, and troubleshooting when remote management is unavailable.',
            details: ['Spans U26–U29', 'Local VGA/display console', 'Exact panel model not specified'],
            electrical: ['Input voltage and frequency: model dependent', 'Power draw: model and brightness dependent', 'Confirm exact values from the monitor rear rating label'],
        },
        {
            id: 'blank-25',
            title: 'Blank Panel',
            shortLabel: 'U25 Blank Panel',
            startU: 25,
            sizeU: 1,
            icon: Server,
            type: 'Passive',
            description: 'A solid filler panel below the display that blocks recirculating exhaust air and separates the display from the pull-out console hardware.',
            details: ['U25 position', 'Passive airflow management', 'Closes one unused rack unit'],
        },
        {
            id: 'tray-24',
            title: 'Tray',
            shortLabel: 'U24 Tray',
            startU: 24,
            sizeU: 1,
            icon: Server,
            type: 'Passive',
            description: 'A fixed rack shelf for supporting non-rackmount console accessories or small devices immediately above the input tray.',
            details: ['U24 position', 'Passive equipment support', 'Load rating depends on the installed tray'],
        },
        {
            id: 'keyboard-tray',
            title: 'Keyboard & Mouse Tray',
            shortLabel: 'Keyboard & Mouse',
            startU: 23,
            sizeU: 1,
            icon: Keyboard,
            type: 'Console',
            description: 'A sliding keyboard and mouse platform that provides direct local input while stowing inside the rack when it is not in use.',
            details: ['U23 position', 'Passive sliding console platform', 'Local keyboard and pointing-device support'],
        },
        {
            id: 'r730',
            title: 'Dell PowerEdge R730',
            shortLabel: 'Dell R730',
            startU: 21,
            sizeU: 2,
            icon: Server,
            type: 'Compute',
            description: 'A 2U general-purpose compute node for virtual machines, containers, infrastructure services, and other processor- or memory-focused lab workloads.',
            details: ['2U dual-socket server', 'Up to two hot-swappable PSUs with 1+1 redundancy', 'Compute-focused virtualization and service workloads'],
            electrical: ['AC input: normally 100–240 V, 50/60 Hz (200–240 V for 750 W Titanium PSU)', 'Supported PSU ratings: 495 W, 750 W, or 1,100 W', 'Actual draw depends on CPU, memory, storage, and accelerator configuration'],
        },
        {
            id: 'r730xd',
            title: 'Dell PowerEdge R730XD',
            shortLabel: 'Dell R730XD',
            startU: 19,
            sizeU: 2,
            icon: HardDrive,
            type: 'Storage',
            description: 'A storage-dense 2U server for bulk disks, lab datasets, virtual-machine storage, backups, and workloads that benefit from the R730XD drive layout.',
            details: ['2U storage-dense server', 'Up to two hot-swappable PSUs with 1+1 redundancy', 'Storage-focused virtualization and data workloads'],
            electrical: ['AC input: normally 100–240 V, 50/60 Hz (200–240 V for 750 W Titanium PSU)', 'Supported PSU ratings: 495 W, 750 W, or 1,100 W', 'Actual draw depends on CPU, memory, drive count, and accelerator configuration'],
        },
        {
            id: 'blank-10',
            title: 'Blank Panel',
            shortLabel: 'U10 Blank Panel',
            startU: 10,
            sizeU: 1,
            icon: Server,
            type: 'Passive',
            description: 'A filler panel closing the lower boundary of the large expansion zone and limiting exhaust-air recirculation through unused rack space.',
            details: ['U10 position', 'Passive airflow management', 'Closes one unused rack unit'],
        },
        {
            id: 'blank-9',
            title: 'Blank Panel',
            shortLabel: 'U9 Blank Panel',
            startU: 9,
            sizeU: 1,
            icon: Server,
            type: 'Passive',
            description: 'A filler panel that closes the final open unit before the power-distribution stack and keeps the lower rack layout visually and thermally separated.',
            details: ['U9 position', 'Passive airflow management', 'Closes one unused rack unit'],
        },
        {
            id: 'apc-ap7921b',
            title: 'APC AP7921B',
            shortLabel: 'APC AP7921B',
            startU: 8,
            sizeU: 1,
            icon: PlugZap,
            type: 'Power',
            description: 'A network-managed switched PDU that distributes rack power through individually controllable outlets for remote restart and load management.',
            details: ['1U single-phase switched PDU', '8 × IEC C13 outlets', 'Remote outlet switching and current metering'],
            electrical: ['Input/output: 208/230 V AC, 50/60 Hz', 'Rated current: 16 A', 'Load capacity: 3.3 kW at 208 V or 3.7 kW at 230 V'],
        },
        {
            id: 'cable-management-7',
            title: 'Cable Management Panel',
            shortLabel: 'U7 Cable Mgmt',
            startU: 7,
            sizeU: 1,
            icon: Cable,
            type: 'Passive',
            description: 'A horizontal organizer that routes power leads cleanly between the two switched PDUs while providing bend and strain control.',
            details: ['U7 position', 'Passive horizontal cable routing', 'Power-lead separation and strain relief'],
        },
        {
            id: 'apc-ap7921',
            title: 'APC AP7921',
            shortLabel: 'APC AP7921',
            startU: 6,
            sizeU: 1,
            icon: PlugZap,
            type: 'Power',
            description: 'A switched rack PDU for remotely controlling eight outlets, monitoring the branch load, and recovering attached equipment without physical access.',
            details: ['1U single-phase switched PDU', '8 × IEC C13 outlets', 'Remote outlet switching and load monitoring'],
            electrical: ['Input/output: 208/230 V AC, 50/60 Hz', 'Rated current: 16 A', 'Load capacity: 3.3 kW at 208 V or 3.7 kW at 230 V'],
        },
        {
            id: 'cable-management-5',
            title: 'Cable Management Panel',
            shortLabel: 'U5 Cable Mgmt',
            startU: 5,
            sizeU: 1,
            icon: Cable,
            type: 'Passive',
            description: 'A horizontal organizer that separates the switched-PDU feeds from the ATS connections and keeps service loops contained.',
            details: ['U5 position', 'Passive horizontal cable routing', 'Power-lead separation and strain relief'],
        },
        {
            id: 'apc-ap4423-ats',
            title: 'APC AP4423 ATS',
            shortLabel: 'APC AP4423 ATS',
            startU: 4,
            sizeU: 1,
            icon: PlugZap,
            type: 'Power',
            description: 'A rack automatic transfer switch that supplies single-corded equipment from one of two independent sources and transfers when the preferred source fails.',
            details: ['1U automatic transfer switch', '2 × IEC C20 inputs', '8 × IEC C13 and 1 × IEC C19 outputs'],
            electrical: ['Rated input/output: 230 V AC, 50/60 Hz', 'Rated current: 16 A; 20 A maximum line current', 'Load capacity: 3,700 VA'],
        },
        {
            id: 'cable-management-3',
            title: 'Cable Management Panel',
            shortLabel: 'U3 Cable Mgmt',
            startU: 3,
            sizeU: 1,
            icon: Cable,
            type: 'Passive',
            description: 'The lowest horizontal organizer, guiding incoming and outgoing power leads between the ATS and bottom equipment shelf.',
            details: ['U3 position', 'Passive horizontal cable routing', 'Bottom-section cable strain relief'],
        },
        {
            id: 'tray-2',
            title: 'Tray',
            shortLabel: 'U2 Tray',
            startU: 2,
            sizeU: 1,
            icon: Server,
            type: 'Passive',
            description: 'A low-mounted fixed shelf for non-rackmount power accessories or other compact equipment, leaving U1 unobstructed beneath it.',
            details: ['U2 position', 'Passive equipment support', 'Load rating depends on the installed tray'],
        },

];

export const rackUnitLabel = (device) => device.sizeU > 1
    ? `U${device.startU}–${device.startU + device.sizeU - 1}`
    : `U${device.startU}`;
